services:
  - type: web
    name: pakistan-recovery-oasis
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
